### ISSUE TITLE
Weird gradients in Now Playing and Library List

### ISSUE THREAD

**Issue by Gamesnic** [JulienMaille/spicetify-dynamic-theme#104]
**Describe the bug**
The main bug is the gradients, if you want me to add the other one purely as feature request, then I can do that.

I think it comes from Spotify recently adding those gradients in the now playing tab, but the gradients pretty much destroy the light mode. As seen in the first screenshot, it's weirdly darkened down right in the text. This gradient is also present in the list view of your library. As seen in the last screenshot, this isn't an issue in dark mode. Another thing is that the text is a bit very saturated in dark mode, could you add an option to change text saturation?

**To Reproduce**
1. Simply use the theme in Light mode and have Now Playing view enabled

**Screenshots**
![image](https://github.com/user-attachments/assets/dc650652-0db5-4331-a092-dc8a6b8454be)
![image](https://github.com/user-attachments/assets/9329b952-2a0f-405b-b105-98fa46749c8d)
![image](https://github.com/user-attachments/assets/5f3c5a50-1246-49c3-becf-9c9f7d58d9ee)

**Desktop Setup**
- Operating System: Windows 11 Stable, Version 10.0.22631 Build 22631
- Spotify: 1.2.51.345.gcc39d911
- Spicetify: 2.38.4
- Theme: if Powershell script downloads latest, 5.4 with fix

**Logs**
```console
index.html:1 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
(anonymous) @ index.html:1
CircularSp-Book.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSp-Bold.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSpTitle-Bold.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSpTitle-Black.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
spicetifyWrapper.js:453 [spicetifyWrapper] Waiting for required webpack modules to load
4151.css:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
favicon.ico:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
spicetifyWrapper.js:474 [spicetifyWrapper] All required webpack modules loaded
image-cdn-fa.spotifycdn.com/image/ab67706c0000da8496d82472f375cfe71f0f2a8e:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
extension.js:8 Initializing Spicetify Marketplace v1.0.2
sidebarConfig.js:169 Uncaught (in promise) TypeError: Spicetify.Snackbar?.enqueueCustomSnackbar is not a function
    at sidebarConfig.js:169:24
extension.js:8 Loaded Marketplace extension
gew4-spclient.spotify.com/social-connect/v2/devices//jam_status:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
gew4-spclient.spotify.com/remote-config-resolver/v3/configuration:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
xpui.js:1 HttpResponseError
    at n.fromResponse (xpui.js:1:1417723)
    at e.onAfterSend (xpui.js:1:1395981)
    at xpui.js:1:1422205
    at async l.fetchCurrentSession (xpui.js:1:1802393)
l @ xpui.js:1
vendor~xpui.js:1 provider:transport resolve error k Object
h @ vendor~xpui.js:1
index.html:1 Uncaught (in promise) k
default-dynamic.js:296 Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLCanvasElement or HTMLImageElement or HTMLVideoElement or ImageBitmap or OffscreenCanvas or SVGImageElement or VideoFrame)'.
    at img.onload (default-dynamic.js:296:17)
pubads_impl.js:33 The following functions are deprecated: googletag.pubads().setTagForChildDirectedTreatment(), googletag.pubads().clearTagForChildDirectedTreatment(), googletag.pubads().setRequestNonPersonalizedAds(), and googletag.pubads().setTagForUnderAgeOfConsent(). Please use googletag.pubads().setPrivacySettings() instead.
tE @ pubads_impl.js:33
xpui.js:1 no-ad
(anonymous) @ xpui.js:1
index.html:1 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
(anonymous) @ index.html:1
16The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
default-dynamic.js:296 Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLCanvasElement or HTMLImageElement or HTMLVideoElement or ImageBitmap or OffscreenCanvas or SVGImageElement or VideoFrame)'.
    at img.onload (default-dynamic.js:296:17)
img.onload @ default-dynamic.js:296
load
pickCoverColor @ default-dynamic.js:293
setTimeout
pickCoverColor @ default-dynamic.js:304
songchange @ default-dynamic.js:275
await in songchange
dispatchEvent @ spicetifyWrapper.js:16
(anonymous) @ spicetifyWrapper.js:973
_dispatchFromStore @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
a @ vendor~xpui.js:1
t @ vendor~xpui.js:1
postMessage
c @ vendor~xpui.js:1
emit @ vendor~xpui.js:1
emit @ xpui.js:1
(anonymous) @ xpui.js:1
(anonymous) @ vendor~xpui.js:1
onSuccess @ xpui.js:1
```

**Comment by JulienMaille** [comment]
Sorry I unfortunately don't have the resource for such feature requests
