### ISSUE TITLE
Bug while starting a song

### ISSUE THREAD

**Issue by sasso220** [JulienMaille/spicetify-dynamic-theme#106]
**Describe the bug**
when I start a song, everything on the screen often disappears

**To Reproduce**
1. Start a song, not always but when it happens, you have to restart spotify
2. After the song starts, everything disappears

**Screenshots**
![immagine_2024-11-24_120539366](https://github.com/user-attachments/assets/16810b3b-7559-40a3-8d1b-08d1eebde6b5)

**Desktop Setup**
- Operating System:  Windows 11
- Spotify:  1.2.50.333.g77514274 
- Spicetify:  2.38.4 
- Theme:  2.7.0 

**Logs**

```console
index.html:1 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
(anonymous) @ index.html:1
CircularSp-Book.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSp-Bold.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSpTitle-Bold.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSpTitle-Black.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
spicetifyWrapper.js:453 [spicetifyWrapper] Waiting for required webpack modules to load
4151.css:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
favicon.ico:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
spicetifyWrapper.js:474 [spicetifyWrapper] All required webpack modules loaded
extension.js:8 Initializing Spicetify Marketplace v1.0.2
sidebarConfig.js:169 Uncaught (in promise) TypeError: Spicetify.Snackbar?.enqueueCustomSnackbar is not a function
    at sidebarConfig.js:169:24
extension.js:8 Loaded Marketplace extension
gew4-spclient.spotify.com/social-connect/v2/devices//jam_status:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
gew4-spclient.spotify.com/remote-config-resolver/v3/configuration:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
xpui.js:1 HttpResponseError
    at n.fromResponse (xpui.js:1:1421208)
    at e.onAfterSend (xpui.js:1:1399466)
    at xpui.js:1:1425690
    at async l.fetchCurrentSession (xpui.js:1:1805878)
l @ xpui.js:1
vendor~xpui.js:1 provider:transport resolve error k Object
h @ vendor~xpui.js:1
index.html:1 Uncaught (in promise) k
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
xpui.js:1 Uncaught (in promise) InternalServerError: GET request to sp://ads/v1/ads/hpto failed with status code 500
    at c.onSuccess (xpui.js:1:1469728)
    at onSuccess (xpui.js:1:1469542)
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
(anonymous) @ index.html:1

```

**Comment by sasso220** [comment]
hi, i still have this problem, is there a solution? thank you
