### ISSUE TITLE
update batch always appearing even after update

### ISSUE THREAD

**Issue by iampickle** [JulienMaille/spicetify-dynamic-theme#107]
**Describe the bug**

**To Reproduce**
1.  Update to the newest release

**Screenshots**
<img width="1196" alt="image" src="https://github.com/user-attachments/assets/8fc5562e-c4fd-4372-b987-f346346d0a13">

**Desktop Setup**
- Operating System: Macos 15.1.1 (24B91)
- Spotify: 1.2.51.345.gcc39d911
- Spicetify: v2.38.5
- Theme: 5.5

**Logs**
```console
 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
(anonymous) @ index.html:1
spicetifyWrapper.js:453 [spicetifyWrapper] Waiting for required webpack modules to load
CircularSp-Book.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSp-Bold.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSpTitle-Bold.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSpTitle-Black.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
favicon.ico:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
4151.css:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
spicetifyWrapper.js:474 [spicetifyWrapper] All required webpack modules loaded
extension.js:8 Initializing Spicetify Marketplace v0.8.9
sidebarConfig.js:169 Uncaught (in promise) TypeError: Spicetify.Snackbar?.enqueueCustomSnackbar is not a function
    at sidebarConfig.js:169:24
extension.js:8 Loaded Marketplace extension
vendor~xpui.js:1 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Pl (vendor~xpui.js:1:2162558)
    at p (vendor~xpui.js:1:2097520)
    at m (vendor~xpui.js:1:2098875)
    at e (vendor~xpui.js:1:2100932)
    at gs (vendor~xpui.js:1:2119011)
    at vc (vendor~xpui.js:1:2167714)
    at ml (vendor~xpui.js:1:2155055)
    at hl (vendor~xpui.js:1:2154983)
    at pl (vendor~xpui.js:1:2154846)
    at il (vendor~xpui.js:1:2151987)
ss @ vendor~xpui.js:1
cat-jam.js?time=1732712655456:1 [CAT-JAM] Extension loaded.
vendor~xpui.js:1 Uncaught (in promise) Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Pl (vendor~xpui.js:1:2162558)
    at p (vendor~xpui.js:1:2097520)
    at m (vendor~xpui.js:1:2098875)
    at e (vendor~xpui.js:1:2100932)
    at gs (vendor~xpui.js:1:2119011)
    at vc (vendor~xpui.js:1:2167714)
    at ml (vendor~xpui.js:1:2155055)
    at hl (vendor~xpui.js:1:2154983)
    at pl (vendor~xpui.js:1:2154846)
    at il (vendor~xpui.js:1:2151987)
gew4-spclient.spotify.com/remote-config-resolver/v3/configuration:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:1 provider:transport resolve error k Object
h @ vendor~xpui.js:1
index.html:1 Uncaught (in promise) k
cat-jam.js?time=1732712655456:1 0
cat-jam.js?time=1732712655456:1 [CAT-JAM] Track BPM: 94.387
cat-jam.js?time=1732712655456:1 [CAT-JAM] Cat jam synchronized, playback rate set to: 0.6966858576911722
xpui.js:1 Detected hard reload. Deleting persisted cache.
12The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
section-marker.js?time=1732712655456:1 waitForElm has waited for 5000  for selector #main > .Root within <body class=​"encore-dark-theme encore-layout-themes section-marker-no-data" style=​"--section-marker-playbar-width:​ 376px;​ --section-marker-playbar-height:​ 12px;​">​…​</body>​flex but it has not yet been found.
(anonymous) @ section-marker.js?time=1732712655456:1
6xpui.js:1 Detected hard reload. Deleting persisted cache.
index.html:1 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
```

**Comment by JulienMaille** [comment]
I suggest to install from the marketplace if you're using it

**Comment by iampickle** [comment]
Okay, I'll do. 
Thx for the response:)

**Comment by andrew-jolley** [comment]
I have installed from the marketplace, and get the same issue
