### ISSUE TITLE
[BUG] No longer automatically switches to system theme, transparent window controls not being obeyed

### ISSUE THREAD

**Issue by ctp9** [JulienMaille/spicetify-dynamic-theme#11]
**Describe the bug**
Automatic theme switching upon opening Spotify no longer works in v2.8 with spicetify v2.6.6. As well, transparent window controls shortcut argument no longer works either.

**To Reproduce**
Open Spotify 1.1.68 with spicetify v2.6.6 and spicetify-dynamic-theme v2.8 and it will not follow system theme (or switch from previous system theme to new system theme when recently applied) - as well as window controls are not transparent.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H1
 - Version 10.0.19043 Build 19043

**Logs**
```
vendor~xpui.js:1 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2353172)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2355454)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2048746
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2595327)
    at As (https://xpui.app.spotify.com/vendor~xpui.js:29:2619179)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2793496)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564835)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2618958)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2603729)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2602651)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2565107
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2793496)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564835)
    at yi (https://xpui.app.spotify.com/vendor~xpui.js:29:2565052)
    at vi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564987)
    at Es (https://xpui.app.spotify.com/vendor~xpui.js:29:2603150)
    at rl (https://xpui.app.spotify.com/vendor~xpui.js:29:2629563)
    at render (https://xpui.app.spotify.com/vendor~xpui.js:29:2632674)
    at https://xpui.app.spotify.com/xpui.js:1:1034419
(anonymous) @ vendor~xpui.js:1
sentry.io/api/114855/envelope/?sentry_key=de32132fc06e4b28965ecf25332c3a25&sentry_version=7:1 Failed to load resource: the server responded with a status of 429 (Too Many Requests)
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/22.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-playlist.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/service-worker.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Comment by JulienMaille** [comment]
This is a spicetify/spotify issue, I can't fix it in my theme
