### ISSUE TITLE
"Explicit" tag doesn't show the "E" 

### ISSUE THREAD

**Issue by immaterials** [JulienMaille/spicetify-dynamic-theme#111]
**Describe the bug**
The explicit tag icon looks fully white (or black, depending on the mode) instead of being the usual "E" icon 

**To Reproduce**
1. Look up any song that has the explicit tag

**Screenshots**

**Dark mode:**

![image](https://github.com/user-attachments/assets/3361c784-cb69-4d40-9b0c-789d57ed9ebf)

**Light mode:**
 
![image](https://github.com/user-attachments/assets/abb9d562-ec94-4a9f-a2e2-fb408ca9a444)

It's like this in everything it shows on. 

**Desktop Setup**
Operating System: Windows 11 Home 24H2
Spotify: 1.2.52.442
Spicetify v2.38.5
Theme: 5.5

**Logs**

```console
CircularSp-Bold.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSpTitle-Bold.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSpTitle-Black.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
spicetifyWrapper.js:453 [spicetifyWrapper] Waiting for required webpack modules to load
4151.css:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
favicon.ico:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
spicetifyWrapper.js:474 [spicetifyWrapper] All required webpack modules loaded
extension.js:8 Initializing Spicetify Marketplace v1.0.2
sidebarConfig.js:169 Uncaught (in promise) TypeError: Spicetify.Snackbar?.enqueueCustomSnackbar is not a function
    at sidebarConfig.js:169:24
extension.js:8 Loaded Marketplace extension
gew1-spclient.spotify.com/remote-config-resolver/v3/configuration:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
gew1-spclient.spotify.com/social-connect/v2/devices//jam_status:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
vendor~xpui.js:1 provider:transport resolve error k Object
h @ vendor~xpui.js:1
xpui.js:1 HttpResponseError
    at n.fromResponse (xpui.js:1:1387907)
    at e.onAfterSend (xpui.js:1:1366360)
    at xpui.js:1:1392582
    at async xu.fetchCurrentSession (xpui.js:1:1270008)
l @ xpui.js:1
index.html:1 Uncaught (in promise) k
40The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
2xpui.js:1 Uncaught (in promise) Error: Command failed with code '1' and reasons 'not_paused'
    at Js (xpui.js:1:1190698)
    at async ko.resume (xpui.js:1:1209560)
api.spotify.com/v1/tracks?ids=:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
xpui.js:1 Uncaught (in promise) Error: slot-not-defined
    at Object.fetchAdForSlot (xpui.js:1:773940)
    at async pe.getSlot (xpui.js:1:813168)
    at async xpui.js:1:647541
find-duplicates.js?time=1733479882275:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')
    at e (find-duplicates.js?time=1733479882275:1:5497)
 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
(anonymous) @ index.html:1
index.html:1 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
(anonymous) @ index.html:1
```

**Comment by gxx7pk** [comment]
i still have this error
