### ISSUE TITLE
My Window Does This When Playing A Song

### ISSUE THREAD

**Issue by leeprky** [JulienMaille/spicetify-dynamic-theme#21]
**Describe the bug**

**To Reproduce**
1.  Play A Song With a fresh spotify & spicetify install

**Screenshots**

![image](https://user-images.githubusercontent.com/71296232/145870099-e31c0181-c12d-45db-bfed-1127e2098976.png)

**Desktop Setup**
- Operating System: Windows 11
- Spotify: 1.1.74.631
- Spicetify: 2.8.3
- Theme: 3.3

**Logs**

```console
spicetifyWrapper.js:879 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
Spicetify._cloneSidebarItem @ spicetifyWrapper.js:879
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2712035)
    at t.r.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2714619)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2321867
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2955910)
    at Is (https://xpui.app.spotify.com/vendor~xpui.js:29:2979642)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3194923)
    at ho (https://xpui.app.spotify.com/vendor~xpui.js:29:2925446)
    at As (https://xpui.app.spotify.com/vendor~xpui.js:29:2979421)
    at ws (https://xpui.app.spotify.com/vendor~xpui.js:29:2964300)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2963222)
c @ vendor~xpui.js:29
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
vendor~xpui.js:29 The buttonLegacy prop has been deprecated. This prop will be removed soon. Please migrate to new button styles by removing this prop.
Read more: https://encore.spotify.net/web/whats-new/green-buttons/?format=web-js
i @ vendor~xpui.js:29
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/696.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/566.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
Vibrant.min.js:390 Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at new b (Vibrant.min.js:390)
    at pickCoverColor (default-dynamic.js:241)
    at MutationObserver.<anonymous> (default-dynamic.js:266)
b @ Vibrant.min.js:390
pickCoverColor @ default-dynamic.js:241
(anonymous) @ default-dynamic.js:266
attributes (async)
_t @ vendor~xpui.js:29
Na @ vendor~xpui.js:29
ks @ vendor~xpui.js:29
t.unstable_runWithPriority @ vendor~xpui.js:29
ho @ vendor~xpui.js:29
Ps @ vendor~xpui.js:29
vs @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
t.unstable_runWithPriority @ vendor~xpui.js:29
ho @ vendor~xpui.js:29
yo @ vendor~xpui.js:29
bo @ vendor~xpui.js:29
gs @ vendor~xpui.js:29
Hr @ vendor~xpui.js:29
(anonymous) @ xpui.js:1
a @ xpui.js:1
_dispatchFromStore @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
a @ vendor~xpui.js:29
t @ vendor~xpui.js:29
postMessage (async)
l @ vendor~xpui.js:29
emit @ vendor~xpui.js:29
emit @ xpui.js:1
(anonymous) @ xpui.js:1
(anonymous) @ vendor~xpui.js:29
onSuccess @ xpui.js:1
```
![image](https://user-images.githubusercontent.com/71296232/145870344-eec2dd90-191e-4821-b0e6-c8646baa05b0.png)

**Other**
Changing the width and height of the canvas fixes it for the current song
![image](https://user-images.githubusercontent.com/71296232/145870543-0834834d-66b3-4de6-9408-16007c2b6842.png)

as well as this: (temp fix ig)
which just to make it match window size fixes it
![image](https://user-images.githubusercontent.com/71296232/145878424-8b4e879a-29be-4e18-9d72-7ee24400d9e2.png)

**Comment by JulienMaille** [comment]
Should be fixed with latest commit, can you update manually?

**Comment by leeprky** [comment]
Yeah just manually downloaded the .js files and put them in the extensions folder and ran the manual install script and its all good now!

Thanks
