### ISSUE TITLE
Theme making Spicetify laggy

### ISSUE THREAD

**Issue by Monstecat45** [JulienMaille/spicetify-dynamic-theme#35]
**Describe the bug**
The theme is making the spicetify laggy and slow response like from 60fps to 20fps

**To Reproduce**
1. apply/install theme

**Screenshots**
Sreen Capture provided - https://user-images.githubusercontent.com/102982195/187375936-2970ca09-722b-439c-9196-ef38c0e2235d.mp4

**Desktop Setup**
- Operating System: Windows 10 Home Single Language, Version 10.0.19004 Build 19044
- Spotify: 1.1.92.647.ga4397eb7

. 1.1.71.560] from `Menu (Three dots top left) > Help > About` -->
- Spicetify: 
- Theme: 

**Logs**
Preloading extensions and themes...
vendor~xpui.js:1 Initializing Spicetify Marketplace v0.7.1
vendor~xpui.js:1 Loaded Marketplace extension
vendor~xpui.js:1 Initializing extension:  Object
vendor~xpui.js:1 Initializing extension:  Object
vendor~xpui.js:1 Initializing extension:  Object
vendor~xpui.js:1 Initializing extension:  Object
xpui.js:1 Uncaught (in promise) NotFoundError: GET request to sp://ads/v1/settings/leaderboard failed with status code 404
    at l.onSuccess (xpui.js:1:1510504)
    at onSuccess (xpui.js:1:1510318)
vendor~xpui.js:1 Enhance feature enabled!
vendor~xpui.js:1 Ads delayed: Adblock.js
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
pubads_impl_2022082501.js:10 The following functions are deprecated: googletag.pubads().setTagForChildDirectedTreatment(), googletag.pubads().clearTagForChildDirectedTreatment(), googletag.pubads().setRequestNonPersonalizedAds(), and googletag.pubads().setTagForUnderAgeOfConsent(). Please use googletag.pubads().setPrivacySettings() instead.
Yw @ pubads_impl_2022082501.js:10
vendor~xpui.js:1 Object
vendor~xpui.js:1 Parsed 33/33 extensions
vendor~xpui.js:1 No more extension results
vendor~xpui.js:1 Object
vendor~xpui.js:1 Parsed 40/40 themes
vendor~xpui.js:1 No more theme results
raw.githubusercontent.com/spicetify/spicetify-marketplace/main/manifest.json:1          Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:1 / <section data-testid=​"home-page">​…​</section>​
vendor~xpui.js:1 Tagging carousel: Episodes for you
raw.githubusercontent.com/3raxton/spicetify-custom-apps-and-extensions/main/manifest.json:1          Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/TheRandomLabs/Scoop-Spotify/master/manifest.json:1          Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/itsmeow/Spicetify-Canvas/master/manifest.json:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/8696.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/1864.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-hpto.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-v2.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/2639.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/8419.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
vendor~xpui.js:1          GET https://raw.githubusercontent.com/getomni/spicetify/main/manifest.json 404
(anonymous) @ vendor~xpui.js:1
L @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
vendor~xpui.js:1          GET https://raw.githubusercontent.com/catppuccin/spicetify/main/manifest.json 404
(anonymous) @ vendor~xpui.js:1
L @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
vendor~xpui.js:1          GET https://raw.githubusercontent.com/schnensch0/ziro/main/manifest.json 404
(anonymous) @ vendor~xpui.js:1
L @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
vendor~xpui.js:1          GET https://raw.githubusercontent.com/axieum/jasmine-spicetify-theme/master/manifest.json 404
(anonymous) @ vendor~xpui.js:1
L @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1

https://user-images.githubusercontent.com/102982195/187375936-2970ca09-722b-439c-9196-ef38c0e2235d.mp4
```console
[paste logs here]
```

**Comment by Monstecat45** [comment]
I found a fix: Enable Hardware Acceleration
