### ISSUE TITLE
A new feature causes the video card to be fully loaded

### ISSUE THREAD

**Issue by gohavelik** [JulienMaille/spicetify-dynamic-theme#42]
**Describe the bug**
A new feature causes the video card to be fully loaded, namely: Video effects in the background load the video card to its fullest.

**Screenshots**
![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/49018160/4d90d89c-0a9e-412f-bea8-d4e1fe1b6924)

**Desktop Setup**
- Operating System: Windows 10 Pro Version 22H2
- Spotify: 64-bit 1.2.16.947.gcfbaa410
- Spicetify: Spicetify v2.22.1
- Theme: newest

**Logs**

```console
[Initializing Spicetify Marketplace v0.8.8
extension.js:1 Loaded Marketplace extension
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
 The following functions are deprecated: googletag.pubads().setTagForChildDirectedTreatment(), googletag.pubads().clearTagForChildDirectedTreatment(), googletag.pubads().setRequestNonPersonalizedAds(), and googletag.pubads().setTagForUnderAgeOfConsent(). Please use googletag.pubads().setPrivacySettings() instead.
xx @ securepubads.g.doubl…1/pubads_impl.js:10
raw.githubusercontent.com/spicetify/spicetify-marketplace/main/manifest.json:1     Failed to load resource: the server responded with a status of 404 ()
default-dynamic.js?time=1690841036329:285 ReferenceError: Vibrant is not defined
    at pickCoverColor (default-dynamic.js?time=1690841036329:277:28)
    at registerCoverListener (default-dynamic.js?time=1690841036329:296:5)
    at default-dynamic.js?time=1690841036329:313:1
pickCoverColor @ default-dynamic.js?time=1690841036329:285
gew4-spclient.spotify.com/remote-config-resolver/v3/configuration:1     Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:29 provider:transport resolve error A Object
f @ vendor~xpui.js:29
index.html:1 Uncaught (in promise) A
vendor~xpui.js:29 NotFoundError: GET request to sp://core-playlist/v1/playlist/spotify%3Aplaylist%3A37i9dQZF1EYkqdzj48dyYq/?responseFormat=protobufJson&start=0&length=0 failed with status code 404
    at l.onSuccess (xpui.js:1:1902350)
    at onSuccess (xpui.js:1:1902164)
onError @ vendor~xpui.js:29
raw.githubusercontent.com/3raxton/spicetify-custom-apps-and-extensions/main/manifest.json:1     Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/TheRandomLabs/Scoop-Spotify/master/manifest.json:1     Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:29 NotFoundError: GET request to sp://core-playlist/v1/playlist/spotify%3Aplaylist%3A37i9dQZF1EYkqdzj48dyYq/?responseFormat=protobufJson&start=0&length=0 failed with status code 404
    at l.onSuccess (xpui.js:1:1902350)
    at onSuccess (xpui.js:1:1902164)
onError @ vendor~xpui.js:29
xpui.js:1 NotFoundError: SUB request to sp://ads/v1/slots/leaderboard failed with status code 404
    at l.onSuccess (xpui.js:1:1902350)
    at onSuccess (xpui.js:1:1902164)
n @ xpui.js:1
xpui.js:1 Uncaught (in promise) NotFoundError: GET request to sp://ads/v1/settings/leaderboard failed with status code 404
    at l.onSuccess (xpui.js:1:1902350)
    at onSuccess (xpui.js:1:1902164)
raw.githubusercontent.com/itsmeow/Spicetify-Canvas/master/manifest.json:1     Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-hpto.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/1274.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/9601.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/5621.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-v2.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/8736.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-collection-songs.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
vendor~xpui.js:29 NotFoundError: GET request to sp://core-playlist/v1/playlist/spotify%3Aplaylist%3A37i9dQZF1EYkqdzj48dyYq/?responseFormat=protobufJson&start=0&length=0 failed with status code 404
    at l.onSuccess (xpui.js:1:1902350)
    at onSuccess (xpui.js:1:1902164)
onError @ vendor~xpui.js:29
h @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.catch (async)
l @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.then (async)
(anonymous) @ vendor~xpui.js:29
Promise.catch (async)
l @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
extension.js:1     GET https://raw.githubusercontent.com/getomni/spicetify/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/schnensch0/ziro/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Darkempire78/Fast-BlockTheSpot-And-Spicetify-Update/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/axieum/jasmine-spicetify-theme/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/yougotwill/Koushi/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Darkempire78/Dracula-Spicetify/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/TheFermi0n/Onepunch/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/spotify-util/ViewPlaylistsWithSong/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/canbeardig/Spicetify-Orchis-Colours-v2/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Dueel/dotfiles/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Vicente015/spicetify-config/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/th3an7/SpicetifyThings/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/3raxton/NoSleep/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/yutakobayashidev/spotify-redesign/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/amanharwara/spicetify-autoVolume/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/aiden04/spicetify-gui/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/nm-nvan/spicetify-twitter/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/shvedes/Gruvboxy/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Aluulu/spicetify-install-script/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/aetriusgx/spicetify-dark-mint/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/canbeardig/Spicetify-Orchis-Colours/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/hrvstr/spicetify-macos-theme/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/AndrisRio/MoereauLibX/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/ethnzhng/Termify/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Daksh777/SpicetifyTheme/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Lylythii/SpicetifyAddons/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/zurrty/spicetify-night/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/misspent/Spicetify-Darkened/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/elizabeth-c-chen/retreon-ziro/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/aaronbeckmann/spicetify-dribbblish-RGB/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Coordinate-Cat/personal-spicetify/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/cyacedev/spicetify-FullBlack/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/h1toru/SPT/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/einzigartigerName/spicetify-history/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/brickfrog/Xresources-spicetify/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/FlafyDev/spotify-listen-together-server/main/manifest.json 404
R @ ex]
```

**Comment by JulienMaille** [comment]
I was afraid the animated background would   generate cou load but couldn't see anything noticeable on my PC. What's your CPU?

**Comment by gohavelik** [comment]
> I was afraid the animated background would generate load but couldn't see anything noticeable on my PC. What's your CPU/GPU ? We could try something like this: `animation: rotate 30s steps(300, end) infinite;`

CPU: 12th Gen Intel(R) Core(TM) i5-12450H
GPU: RTX 3050 L 4gb

**Comment by JulienMaille** [comment]
Wut? I was peaking at 15% load on my integrated Intel iris card. With latest commit it's below 8%

**Comment by JulienMaille** [comment]
Can you try latest update? Animation should take less gpu and there's now an option to disable it
![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/182520/1d286062-6ed1-44f9-8b49-20ea178ca1f9)

**Comment by Ridoou** [comment]
That's weird (even if he's on the old one), but with the new one even on my old laptop with a shitty HD 4600 (who come with i5/i7 series 4000) I got only 25 to 35%) : 

![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/6918077/fd7ca520-bc82-4fbb-9a9a-e37953cf2561)
