### ISSUE TITLE
Themes dont working

### ISSUE THREAD

**Issue by covidjoiner** [JulienMaille/spicetify-dynamic-theme#60]
**Describe the bug**
- Spotify updated. Themes are broken, its no more dynamic-theme anymore, need to fix.

**To Reproduce**
No steps. Just download theme and its just dont working.

**Screenshots**
![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/96987480/ce482a31-9108-4918-bd8f-6077ddca4e48)
![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/96987480/92d18ff3-38ed-4fbe-849e-5eddd9e1b4e2)
![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/96987480/0c3f11b9-395e-4096-b17b-33df58572515)

**Desktop Setup**
- Operating System: [Windows 10]
- Spotify: [1.2.31.1205]
- Spicetify: [2.31.3]
- Theme: [4.8]

```console
 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
(anonymous) @ index.html:1
writeify.js:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
api.github.com/repos/spicetify/spicetify-cli/releases/latest:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
vendor~xpui.js:1 Initializing Spicetify Marketplace v0.9.4
xpui.js:1 Uncaught (in promise) NotFoundError: GET request to sp://ads/v1/settings/leaderboard failed with status code 404
    at l.onSuccess (xpui.js:1:2243666)
    at onSuccess (xpui.js:1:2243480)
vendor~xpui.js:1 TypeError: Cannot read properties of undefined (reading 'slice')
    at checkForUpdate (spicetifyWrapper.js:2379:27)
(anonymous) @ vendor~xpui.js:1
vendor~xpui.js:1 Loaded Marketplace extension
api.github.com/repos/JulienMaille/spicetify-dynamic-theme/releases/latest:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
vendor~xpui.js:1 [Adblock] Ads disabled Object
xpui.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getProductState')
    at p.handleProductStateUpdate (xpui.js:1:2412025)
    at p._dispatchFromStore (vendor~xpui.js:1:629844)
    at p.emitSync (vendor~xpui.js:1:631313)
    at s.emitSync (xpui.js:1:2251285)
    at s.emitProductStateUpdate (xpui.js:1:2425971)
    at xpui.js:1:2048468
    at vendor~xpui.js:1:5546410
    at onSuccess (xpui.js:1:2252064)
default-dynamic.js?time=1708100911735:1 Uncaught SyntaxError: Identifier 'current' has already been declared (at default-dynamic.js?time=1708100911735:1:1)
xpui.js:1 Uncaught (in promise) Error: GET request to https://api.spotify.com/v1/albums/4IcBcb1v7U18kioUMrWkmf request failed with error code -1 (Resolver not found!)
    at l.onFailure (xpui.js:1:2243919)
    at onFailure (xpui.js:1:2243521)
vendor~xpui.js:1 [Adblock] Ads disabled Object
gew1-spclient.spotify.com/remote-config-resolver/v3/configuration:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:1 provider:transport resolve error T Object
(anonymous) @ vendor~xpui.js:1
index.html:1 Uncaught (in promise) T
api.github.com/repos/surfbryce/beautiful-lyrics/contents/dist/beautiful-lyrics.js:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
api.github.com/repos/surfbryce/beautiful-lyrics/git/blobs/undefined:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
vendor~xpui.js:1 Error: InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
(anonymous) @ vendor~xpui.js:1
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
beautiful-lyrics.js?time=1708100911474:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Text')
    at Yn.n.Source.n.NaturalAlignment (beautiful-lyrics.js?time=1708100911474:1:5098582)
    at Yn (beautiful-lyrics.js?time=1708100911474:3:509)
    at beautiful-lyrics.js?time=1708100911474:3:4442
xpui.js:1 Uncaught (in promise) Error: GET request to https://api.spotify.com/v1/albums/5PuTLKpHSO4pJjYCia0djn request failed with error code -1 (Resolver not found!)
    at l.onFailure (xpui.js:1:2243919)
    at onFailure (xpui.js:1:2243521)
xpui.js:1 Uncaught (in promise) Error: GET request to https://api.spotify.com/v1/albums/5dfKkLx9NF3xgwKo3pfxrq request failed with error code -1 (Resolver not found!)
    at l.onFailure (xpui.js:1:2243919)
    at onFailure (xpui.js:1:2243521)
xpui.js:1 Uncaught (in promise) Error: GET request to https://api.spotify.com/v1/albums/3Wm96XwUfNEfVCTYmyQmBH request failed with error code -1 (Resolver not found!)
    at l.onFailure (xpui.js:1:2243919)
    at onFailure (xpui.js:1:2243521)
xpui.js:1 Uncaught (in promise) Error: GET request to https://api.spotify.com/v1/albums/5dfKkLx9NF3xgwKo3pfxrq request failed with error code -1 (Resolver not found!)
    at l.onFailure (xpui.js:1:2243919)
    at onFailure (xpui.js:1:2243521)
xpui.js:1 Uncaught (in promise) Error: GET request to https://api.spotify.com/v1/albums/5EDnWffEsv2TTRyMPMufl7 request failed with error code -1 (Resolver not found!)
    at l.onFailure (xpui.js:1:2243919)
    at onFailure (xpui.js:1:2243521)
xpui.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getProductState')
    at p.handleProductStateUpdate (xpui.js:1:2412025)
    at p._dispatchFromStore (vendor~xpui.js:1:629844)
    at p.emitSync (vendor~xpui.js:1:631313)
    at s.emitSync (xpui.js:1:2251285)
    at s.emitProductStateUpdate (xpui.js:1:2425971)
    at xpui.js:1:2048468
    at vendor~xpui.js:1:5546410
    at onSuccess (xpui.js:1:2252064)
handleProductStateUpdate @ xpui.js:1
_dispatchFromStore @ vendor~xpui.js:1
emitSync @ vendor~xpui.js:1
emitSync @ xpui.js:1
emitProductStateUpdate @ xpui.js:1
(anonymous) @ xpui.js:1
(anonymous) @ vendor~xpui.js:1
onSuccess @ xpui.js:1
vendor~xpui.js:1 [Adblock] Ads disabled {audio: c, vto: {…}, hpto: H, billboard: E, leaderboard: ie, …}
vendor~xpui.js:1 
        
        
       GET https://api.github.com/repos/surfbryce/beautiful-lyrics/contents/dist/beautiful-lyrics.js 403 (Forbidden)
(anonymous) @ vendor~xpui.js:1
c1 @ beautiful-lyrics.js?time=1708100911474:3
i @ vendor~xpui.js:1
vendor~xpui.js:1 
        
        
       GET https://api.github.com/repos/surfbryce/beautiful-lyrics/git/blobs/undefined 403 (Forbidden)
(anonymous) @ vendor~xpui.js:1
(anonymous) @ beautiful-lyrics.js?time=1708100911474:3
Promise.then (async)
c1 @ beautiful-lyrics.js?time=1708100911474:3
i @ vendor~xpui.js:1
vendor~xpui.js:1 Error: InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
(anonymous) @ vendor~xpui.js:1
(anonymous) @ beautiful-lyrics.js?time=1708100911474:5
Promise.catch (async)
c1 @ beautiful-lyrics.js?time=1708100911474:5
i @ vendor~xpui.js:1
```

**Comment by vjt4** [comment]
syncing does not work either

**Comment by JulienMaille** [comment]
Please have a look at the warning here:
https://github.com/spicetify/spicetify-cli/releases/tag/v2.31.3
