### ISSUE TITLE
Changing song does not change the forecolour of the application.

### ISSUE THREAD

**Issue by TrueReassembly** [JulienMaille/spicetify-dynamic-theme#62]
**Describe the bug**

When changing song, the text colour and accents do not change. The only way to make them change is to run ```spicetify apply``` in the powershell.

**To Reproduce**
1. Change the song and observe

**Screenshots**

**Desktop Setup**
- Operating System:  Windows 11
- Spotify:  1.2.31.1205.g4d59ad7c
- Spicetify:  2.31.3
- Theme:  4.8

**Logs**

```console
xpui.js:1 Uncaught (in promise) Error: GET request to https://api.spotify.com/v1/albums/1Wb1Eno6kPJheNHBYI58fq request failed with error code -1 (Resolver not found!)
    at l.onFailure (xpui.js:1:2243919)
    at onFailure (xpui.js:1:2243521)
xpui.js:1 Uncaught (in promise) Error: GET request to https://api.spotify.com/v1/albums/2VrpzWjnsiELWKXOJAFhme request failed with error code -1 (Resolver not found!)
    at l.onFailure (xpui.js:1:2243919)
    at onFailure (xpui.js:1:2243521)
xpui.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getProductState')
    at p.handleProductStateUpdate (xpui.js:1:2412025)
    at p._dispatchFromStore (vendor~xpui.js:1:629844)
    at p.emitSync (vendor~xpui.js:1:631313)
    at s.emitSync (xpui.js:1:2251285)
    at s.emitProductStateUpdate (xpui.js:1:2425971)
    at xpui.js:1:2048468
    at vendor~xpui.js:1:5546410
    at onSuccess (xpui.js:1:2252064)
```

**Comment by vjt4** [comment]
have the same issue. It changes it once, then never again.

**Comment by Samfire2k2** [comment]
same issue too

**Comment by Samfire2k2** [comment]
it works again somehow

**Comment by JulienMaille** [comment]
Please try https://github.com/spicetify/spicetify-cli/releases/tag/v2.32.1

**Comment by vjt4** [comment]
That seemed to work on my end thanks.

**Comment by TrueReassembly** [comment]
This also works for me now, Thank you!
