### ISSUE TITLE
Color does not change after the song changes unless the user restarts the app

### ISSUE THREAD

**Issue by hgt27** [JulienMaille/spicetify-dynamic-theme#64]
**Describe the bug**
color is not updating when the song changes, only changes the color when restarting spotify

**To Reproduce**
1. Install last version with spicetify

**Screenshots**
normal
![pic 1 normal](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/71899602/d0f91d1c-c0cd-47a6-a658-fbdca99df2b2)>
color dose not change after the song changes or user skip
![pic 2 color dose not change](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/71899602/cb0348c1-22b6-429c-93f5-325a9ef6eafe)
color changed after restart
<![pic 3 color changed after restart](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/71899602/4d82187a-234c-42d7-8c8c-c33b76285335)

**Desktop Setup**
- Operating System: Windows 10 Pro
- Spotify: 1.2.31.1205.g4d59ad7c
- Spicetify: 2.32.1
- Theme: 4.8

**Logs**

```console
[index.html:1 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
(anonymous) @ index.html:1
api.github.com/repos/spicetify/spicetify-cli/releases/latest:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
spicetifyWrapper.js:2589 TypeError: Cannot read properties of undefined (reading 'slice')
    at checkForUpdate (spicetifyWrapper.js:2477:27)
checkForUpdate @ spicetifyWrapper.js:2589
xpui.js:1 Failed to resolve endpoints via x-resolve. Using fallbacks! Error: x-resolve request timed out after 3000 ms
    at xpui.js:1:2426001
    at async ee._endpointsProvider (xpui.js:1:2426433)
(anonymous) @ xpui.js:1
spclient.wg.spotify.com/remote-config-resolver/v3/configuration:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:1 provider:transport resolve error T Object
f @ vendor~xpui.js:1
index.html:1 Uncaught (in promise) T
spclient.wg.spotify.com/social-connect/v2/sessions/current:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
extension.js:8 Initializing Spicetify Marketplace v0.9.4
api.github.com/repos/JulienMaille/spicetify-dynamic-theme/releases/latest:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
extension.js:8 Loaded Marketplace extension
api.github.com/repos/Delusoire/spicetify-extensions/contents/dist/show-the-genres/app.js:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
prism.mjs?time=1708969800461:3 Uncaught (in promise) DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at https://cdn.jsdelivr.net/gh/Delusoire/spicetify-extensions@main/dist/show-the-genres/prism.mjs?time=1708969800461:3:19
default-dynamic.js:182 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'metadata')
    at Array.songchange (default-dynamic.js:182:49)
    at Object.dispatchEvent (spicetifyWrapper.js:19:14)
    at p.<anonymous> (spicetifyWrapper.js:907:21)
    at p._dispatchFromStore (vendor~xpui.js:1:629851)
    at Array.<anonymous> (vendor~xpui.js:1:631159)
    at a (vendor~xpui.js:1:628392)
    at t (vendor~xpui.js:1:628850)
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
section-marker.js?time=1708969800463:1 waitForElm has waited for 5000  for selector #main > .Root within <body class=​"section-marker-no-data" style=​"--section-marker-playbar-width:​ 513px;​ --section-marker-playbar-height:​ 12px;​">​…​</body>​flex but it has not yet been found.
(anonymous) @ section-marker.js?time=1708969800463:1
xpui.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getProductState')
    at p.handleProductStateUpdate (xpui.js:1:2414972)
    at p._dispatchFromStore (vendor~xpui.js:1:629851)
    at p.emitSync (vendor~xpui.js:1:631320)
    at s.emitSync (xpui.js:1:2254232)
    at s.emitProductStateUpdate (xpui.js:1:2428918)
    at xpui.js:1:2051415
    at vendor~xpui.js:1:5546417
    at onSuccess (xpui.js:1:2255011)
handleProductStateUpdate @ xpui.js:1
_dispatchFromStore @ vendor~xpui.js:1
emitSync @ vendor~xpui.js:1
emitSync @ xpui.js:1
emitProductStateUpdate @ xpui.js:1
(anonymous) @ xpui.js:1
(anonymous) @ vendor~xpui.js:1
onSuccess @ xpui.js:1
playing-source.js?time=1708969800463:1 PLAYING-SOURCE: Unknown context for provider undefined with URI undefined 
 null {timestamp: 1708969844757, context: {…}, index: {…}, item: {…}, shuffle: false, …}
O @ playing-source.js?time=1708969800463:1
(anonymous) @ playing-source.js?time=1708969800463:1
dispatchEvent @ spicetifyWrapper.js:19
(anonymous) @ spicetifyWrapper.js:923
section-marker.js?time=1708969800463:1 SECTION-MARKER: Failed to get audio data for spotify:track:1QlEnnc6QPldTwYgF2a7dQ Error: GET request to wg://audio-attributes/v1/audio-analysis/1QlEnnc6QPldTwYgF2a7dQ?format=json request failed with error code -1 (Resolver not found!)
    at l.onFailure (xpui.js:1:2246866)
    at onFailure (xpui.js:1:2246468)
(anonymous) @ section-marker.js?time=1708969800463:1
Promise.catch (async)
n @ section-marker.js?time=1708969800463:1
(anonymous) @ section-marker.js?time=1708969800463:1
dispatchEvent @ spicetifyWrapper.js:19
(anonymous) @ spicetifyWrapper.js:923
default-dynamic.js:182 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'metadata')
    at Array.songchange (default-dynamic.js:182:49)
    at Object.dispatchEvent (spicetifyWrapper.js:19:14)
    at p.<anonymous> (spicetifyWrapper.js:907:21)
    at p._dispatchFromStore (vendor~xpui.js:1:629851)
    at Array.<anonymous> (vendor~xpui.js:1:631159)
    at a (vendor~xpui.js:1:628392)
    at t (vendor~xpui.js:1:628850)
songchange @ default-dynamic.js:182
dispatchEvent @ spicetifyWrapper.js:19
(anonymous) @ spicetifyWrapper.js:907
_dispatchFromStore @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
a @ vendor~xpui.js:1
t @ vendor~xpui.js:1
postMessage (async)
c @ vendor~xpui.js:1
emit @ vendor~xpui.js:1
emit @ xpui.js:1
(anonymous) @ xpui.js:1
(anonymous) @ vendor~xpui.js:1
onSuccess @ xpui.js:1
section-marker.js?time=1708969800463:1 SECTION-MARKER: Failed to get audio data for spotify:track:2eS1sLDForZST4mq6Presu Error: GET request to wg://audio-attributes/v1/audio-analysis/2eS1sLDForZST4mq6Presu?format=json request failed with error code -1 (Resolver not found!)
    at l.onFailure (xpui.js:1:2246866)
    at onFailure (xpui.js:1:2246468)
(anonymous) @ section-marker.js?time=1708969800463:1
Promise.catch (async)
n @ section-marker.js?time=1708969800463:1
(anonymous) @ section-marker.js?time=1708969800463:1
dispatchEvent @ spicetifyWrapper.js:19
(anonymous) @ spicetifyWrapper.js:923
vendor~xpui.js:1 
        
        
       GET https://spclient.wg.spotify.com/color-lyrics/v2/track/3HeZam86SuxGp1wZ3XMIjE/image/spotify%3Aimage%3Aab67616d0000b2738f98a497e1c30b2dd678a450?format=json&vocalRemoval=false&market=from_token 408 (Request Timeout)
N @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
_tick @ vendor~xpui.js:1
start @ vendor~xpui.js:1
_sendRetriedRequest @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
_sendRequest @ vendor~xpui.js:1
request @ vendor~xpui.js:1
send @ xpui.js:1
send @ xpui.js:1
r @ xpui.js:1
(anonymous) @ xpui.js:1
queryFn @ xpui.js:1
fetchFn @ vendor~xpui.js:1
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
setOptions @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
setTimeout (async)
o @ vendor~xpui.js:1
a @ vendor~xpui.js:1
batch @ vendor~xpui.js:1
#s @ vendor~xpui.js:1
setData @ vendor~xpui.js:1
onSuccess @ vendor~xpui.js:1
m @ vendor~xpui.js:1
Promise.then (async)
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
onSubscribe @ vendor~xpui.js:1
subscribe @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Ma @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
setTimeout (async)
o @ vendor~xpui.js:1
a @ vendor~xpui.js:1
batch @ vendor~xpui.js:1
#s @ vendor~xpui.js:1
setData @ vendor~xpui.js:1
onSuccess @ vendor~xpui.js:1
m @ vendor~xpui.js:1
Promise.then (async)
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
setOptions @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
rl @ vendor~xpui.js:1
S @ vendor~xpui.js:1
R @ vendor~xpui.js:1
vendor~xpui.js:1 
        
        
       GET https://spclient.wg.spotify.com/color-lyrics/v2/track/3HeZam86SuxGp1wZ3XMIjE/image/spotify%3Aimage%3Aab67616d0000b2738f98a497e1c30b2dd678a450?format=json&vocalRemoval=false&market=from_token 408 (Request Timeout)
N @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
_tick @ vendor~xpui.js:1
start @ vendor~xpui.js:1
_sendRetriedRequest @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
_sendRequest @ vendor~xpui.js:1
request @ vendor~xpui.js:1
send @ xpui.js:1
send @ xpui.js:1
r @ xpui.js:1
(anonymous) @ xpui.js:1
queryFn @ xpui.js:1
fetchFn @ vendor~xpui.js:1
v @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
Promise.catch (async)
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
setOptions @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
setTimeout (async)
o @ vendor~xpui.js:1
a @ vendor~xpui.js:1
batch @ vendor~xpui.js:1
#s @ vendor~xpui.js:1
setData @ vendor~xpui.js:1
onSuccess @ vendor~xpui.js:1
m @ vendor~xpui.js:1
Promise.then (async)
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
onSubscribe @ vendor~xpui.js:1
subscribe @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Ma @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
setTimeout (async)
o @ vendor~xpui.js:1
a @ vendor~xpui.js:1
batch @ vendor~xpui.js:1
#s @ vendor~xpui.js:1
setData @ vendor~xpui.js:1
onSuccess @ vendor~xpui.js:1
m @ vendor~xpui.js:1
Promise.then (async)
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
setOptions @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
rl @ vendor~xpui.js:1
S @ vendor~xpui.js:1
R @ vendor~xpui.js:1
vendor~xpui.js:1 
        
        
       GET https://spclient.wg.spotify.com/color-lyrics/v2/track/3HeZam86SuxGp1wZ3XMIjE/image/spotify%3Aimage%3Aab67616d0000b2738f98a497e1c30b2dd678a450?format=json&vocalRemoval=false&market=from_token 408 (Request Timeout)
N @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
_tick @ vendor~xpui.js:1
start @ vendor~xpui.js:1
_sendRetriedRequest @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
_sendRequest @ vendor~xpui.js:1
request @ vendor~xpui.js:1
send @ xpui.js:1
send @ xpui.js:1
r @ xpui.js:1
(anonymous) @ xpui.js:1
queryFn @ xpui.js:1
fetchFn @ vendor~xpui.js:1
v @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
Promise.catch (async)
v @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
Promise.catch (async)
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
setOptions @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
setTimeout (async)
o @ vendor~xpui.js:1
a @ vendor~xpui.js:1
batch @ vendor~xpui.js:1
#s @ vendor~xpui.js:1
setData @ vendor~xpui.js:1
onSuccess @ vendor~xpui.js:1
m @ vendor~xpui.js:1
Promise.then (async)
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
onSubscribe @ vendor~xpui.js:1
subscribe @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Ma @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
setTimeout (async)
o @ vendor~xpui.js:1
a @ vendor~xpui.js:1
batch @ vendor~xpui.js:1
#s @ vendor~xpui.js:1
setData @ vendor~xpui.js:1
onSuccess @ vendor~xpui.js:1
m @ vendor~xpui.js:1
Promise.then (async)
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
setOptions @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
rl @ vendor~xpui.js:1
S @ vendor~xpui.js:1
R @ vendor~xpui.js:1
vendor~xpui.js:1 
        
        
       GET https://spclient.wg.spotify.com/color-lyrics/v2/track/3HeZam86SuxGp1wZ3XMIjE/image/spotify%3Aimage%3Aab67616d0000b2738f98a497e1c30b2dd678a450?format=json&vocalRemoval=false&market=from_token 408 (Request Timeout)
N @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
_tick @ vendor~xpui.js:1
start @ vendor~xpui.js:1
_sendRetriedRequest @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
_sendRequest @ vendor~xpui.js:1
request @ vendor~xpui.js:1
send @ xpui.js:1
send @ xpui.js:1
r @ xpui.js:1
(anonymous) @ xpui.js:1
queryFn @ xpui.js:1
fetchFn @ vendor~xpui.js:1
v @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
Promise.catch (async)
v @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
Promise.catch (async)
v @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
Promise.catch (async)
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
setOptions @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
setTimeout (async)
o @ vendor~xpui.js:1
a @ vendor~xpui.js:1
batch @ vendor~xpui.js:1
#s @ vendor~xpui.js:1
setData @ vendor~xpui.js:1
onSuccess @ vendor~xpui.js:1
m @ vendor~xpui.js:1
Promise.then (async)
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
onSubscribe @ vendor~xpui.js:1
subscribe @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Ma @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
setTimeout (async)
o @ vendor~xpui.js:1
a @ vendor~xpui.js:1
batch @ vendor~xpui.js:1
#s @ vendor~xpui.js:1
setData @ vendor~xpui.js:1
onSuccess @ vendor~xpui.js:1
m @ vendor~xpui.js:1
Promise.then (async)
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
setOptions @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
rl @ vendor~xpui.js:1
S @ vendor~xpui.js:1
R @ vendor~xpui.js:1
default-dynamic.js:182 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'metadata')
    at Array.songchange (default-dynamic.js:182:49)
    at Object.dispatchEvent (spicetifyWrapper.js:19:14)
    at p.<anonymous> (spicetifyWrapper.js:907:21)
    at p._dispatchFromStore (vendor~xpui.js:1:629851)
    at Array.<anonymous> (vendor~xpui.js:1:631159)
    at a (vendor~xpui.js:1:628392)
    at t (vendor~xpui.js:1:628850)
songchange @ default-dynamic.js:182
dispatchEvent @ spicetifyWrapper.js:19
(anonymous) @ spicetifyWrapper.js:907
_dispatchFromStore @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
a @ vendor~xpui.js:1
t @ vendor~xpui.js:1
postMessage (async)
c @ vendor~xpui.js:1
emit @ vendor~xpui.js:1
emit @ xpui.js:1
(anonymous) @ xpui.js:1
(anonymous) @ vendor~xpui.js:1
onSuccess @ xpui.js:1
vendor~xpui.js:1 
        
        
       GET https://spclient.wg.spotify.com/color-lyrics/v2/track/3HeZam86SuxGp1wZ3XMIjE/image/spotify%3Aimage%3Aab67616d0000b2738f98a497e1c30b2dd678a450?format=json&vocalRemoval=false&market=from_token 408 (Request Timeout)
N @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
_tick @ vendor~xpui.js:1
start @ vendor~xpui.js:1
_sendRetriedRequest @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
_sendRequest @ vendor~xpui.js:1
request @ vendor~xpui.js:1
send @ xpui.js:1
send @ xpui.js:1
r @ xpui.js:1
(anonymous) @ xpui.js:1
queryFn @ xpui.js:1
fetchFn @ vendor~xpui.js:1
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
onSubscribe @ vendor~xpui.js:1
subscribe @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Ma @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
setTimeout (async)
o @ vendor~xpui.js:1
a @ vendor~xpui.js:1
batch @ vendor~xpui.js:1
#s @ vendor~xpui.js:1
setData @ vendor~xpui.js:1
onSuccess @ vendor~xpui.js:1
m @ vendor~xpui.js:1
Promise.then (async)
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
setOptions @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
rl @ vendor~xpui.js:1
S @ vendor~xpui.js:1
R @ vendor~xpui.js:1
section-marker.js?time=1708969800463:1 SECTION-MARKER: Failed to get audio data for spotify:track:3HeZam86SuxGp1wZ3XMIjE Error: GET request to wg://audio-attributes/v1/audio-analysis/3HeZam86SuxGp1wZ3XMIjE?format=json request failed with error code -1 (Resolver not found!)
    at l.onFailure (xpui.js:1:2246866)
    at onFailure (xpui.js:1:2246468)
(anonymous) @ section-marker.js?time=1708969800463:1
Promise.catch (async)
n @ section-marker.js?time=1708969800463:1
(anonymous) @ section-marker.js?time=1708969800463:1
dispatchEvent @ spicetifyWrapper.js:19
(anonymous) @ spicetifyWrapper.js:923
vendor~xpui.js:1 
        
        
       GET https://spclient.wg.spotify.com/color-lyrics/v2/track/3HeZam86SuxGp1wZ3XMIjE/image/spotify%3Aimage%3Aab67616d0000b2738f98a497e1c30b2dd678a450?format=json&vocalRemoval=false&market=from_token 408 (Request Timeout)
N @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
_tick @ vendor~xpui.js:1
start @ vendor~xpui.js:1
_sendRetriedRequest @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
_sendRequest @ vendor~xpui.js:1
request @ vendor~xpui.js:1
send @ xpui.js:1
send @ xpui.js:1
r @ xpui.js:1
(anonymous) @ xpui.js:1
queryFn @ xpui.js:1
fetchFn @ vendor~xpui.js:1
v @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
Promise.catch (async)
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
onSubscribe @ vendor~xpui.js:1
subscribe @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Ma @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
setTimeout (async)
o @ vendor~xpui.js:1
a @ vendor~xpui.js:1
batch @ vendor~xpui.js:1
#s @ vendor~xpui.js:1
setData @ vendor~xpui.js:1
onSuccess @ vendor~xpui.js:1
m @ vendor~xpui.js:1
Promise.then (async)
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
setOptions @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
rl @ vendor~xpui.js:1
S @ vendor~xpui.js:1
R @ vendor~xpui.js:1
vendor~xpui.js:1 
        
        
       GET https://spclient.wg.spotify.com/color-lyrics/v2/track/3HeZam86SuxGp1wZ3XMIjE/image/spotify%3Aimage%3Aab67616d0000b2738f98a497e1c30b2dd678a450?format=json&vocalRemoval=false&market=from_token 408 (Request Timeout)
N @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
_tick @ vendor~xpui.js:1
start @ vendor~xpui.js:1
_sendRetriedRequest @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
_sendRequest @ vendor~xpui.js:1
request @ vendor~xpui.js:1
send @ xpui.js:1
send @ xpui.js:1
r @ xpui.js:1
(anonymous) @ xpui.js:1
queryFn @ xpui.js:1
fetchFn @ vendor~xpui.js:1
v @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
Promise.catch (async)
v @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
Promise.catch (async)
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
onSubscribe @ vendor~xpui.js:1
subscribe @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Ma @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
setTimeout (async)
o @ vendor~xpui.js:1
a @ vendor~xpui.js:1
batch @ vendor~xpui.js:1
#s @ vendor~xpui.js:1
setData @ vendor~xpui.js:1
onSuccess @ vendor~xpui.js:1
m @ vendor~xpui.js:1
Promise.then (async)
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
setOptions @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
rl @ vendor~xpui.js:1
S @ vendor~xpui.js:1
R @ vendor~xpui.js:1
vendor~xpui.js:1 
        
        
       GET https://spclient.wg.spotify.com/color-lyrics/v2/track/3HeZam86SuxGp1wZ3XMIjE/image/spotify%3Aimage%3Aab67616d0000b2738f98a497e1c30b2dd678a450?format=json&vocalRemoval=false&market=from_token 408 (Request Timeout)
N @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
_tick @ vendor~xpui.js:1
start @ vendor~xpui.js:1
_sendRetriedRequest @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
_sendRequest @ vendor~xpui.js:1
request @ vendor~xpui.js:1
send @ xpui.js:1
send @ xpui.js:1
r @ xpui.js:1
(anonymous) @ xpui.js:1
queryFn @ xpui.js:1
fetchFn @ vendor~xpui.js:1
v @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
Promise.catch (async)
v @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
Promise.catch (async)
v @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Promise.then (async)
(anonymous) @ vendor~xpui.js:1
Promise.catch (async)
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
onSubscribe @ vendor~xpui.js:1
subscribe @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Ma @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
setTimeout (async)
o @ vendor~xpui.js:1
a @ vendor~xpui.js:1
batch @ vendor~xpui.js:1
#s @ vendor~xpui.js:1
setData @ vendor~xpui.js:1
onSuccess @ vendor~xpui.js:1
m @ vendor~xpui.js:1
Promise.then (async)
v @ vendor~xpui.js:1
u @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#F @ vendor~xpui.js:1
setOptions @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
oc @ vendor~xpui.js:1
Al @ vendor~xpui.js:1
ll @ vendor~xpui.js:1
Ko @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Sl @ vendor~xpui.js:1
rl @ vendor~xpui.js:1
S @ vendor~xpui.js:1
R @ vendor~xpui.js:1]
```

**Comment by hgt27** [comment]
Workaround : add the following argument  `--disable-web-security` in the shortcut path
